// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXb8AfISCX9bOgi_GhuqyGj669MEKLzco',
    appId: '1:562237159971:web:c7a2ad6288232571304f96',
    messagingSenderId: '562237159971',
    projectId: 'random-animal-parts-site',
    authDomain: 'random-animal-parts-site.firebaseapp.com',
    storageBucket: 'random-animal-parts-site.appspot.com',
    measurementId: 'G-HJQQDB4H9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_TH_JbSdRda9YrHMY50G6Uko8yxu4t0',
    appId: '1:562237159971:android:d562945a21bb1b34304f96',
    messagingSenderId: '562237159971',
    projectId: 'random-animal-parts-site',
    storageBucket: 'random-animal-parts-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYDJ7bV-XbqNcaKuJ4OKSQwCUu2o_hKE',
    appId: '1:562237159971:ios:2ab7301aaa0482a5304f96',
    messagingSenderId: '562237159971',
    projectId: 'random-animal-parts-site',
    storageBucket: 'random-animal-parts-site.appspot.com',
    iosBundleId: 'com.randomanimalparts.randomAnimalPartsSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBYDJ7bV-XbqNcaKuJ4OKSQwCUu2o_hKE',
    appId: '1:562237159971:ios:6a9c3ceb5e08161b304f96',
    messagingSenderId: '562237159971',
    projectId: 'random-animal-parts-site',
    storageBucket: 'random-animal-parts-site.appspot.com',
    iosBundleId: 'com.randomanimalparts.randomAnimalPartsSite.RunnerTests',
  );
}
